# Generated by Django 2.1.7 on 2019-04-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='problem_discription',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(),
        ),
    ]
